# Form implementation generated from reading ui file 'UDFSlot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormSlot(object):
    def setupUi(self, FormSlot):
        FormSlot.setObjectName("FormSlot")
        FormSlot.resize(242, 87)
        self.formLayout = QtWidgets.QFormLayout(FormSlot)
        self.formLayout.setObjectName("formLayout")
        self.lbel = QtWidgets.QLabel(parent=FormSlot)
        self.lbel.setObjectName("lbel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbel)
        self.btnTest = QtWidgets.QPushButton(parent=FormSlot)
        self.btnTest.setObjectName("btnTest")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btnTest)
        self.lcdCounts = QtWidgets.QLCDNumber(parent=FormSlot)
        self.lcdCounts.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.lcdCounts.setLineWidth(1)
        self.lcdCounts.setSmallDecimalPoint(True)
        self.lcdCounts.setDigitCount(12)
        self.lcdCounts.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdCounts.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.lcdCounts.setProperty("value", 0.0)
        self.lcdCounts.setProperty("intValue", 0)
        self.lcdCounts.setObjectName("lcdCounts")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lcdCounts)

        self.retranslateUi(FormSlot)
        QtCore.QMetaObject.connectSlotsByName(FormSlot)

    def retranslateUi(self, FormSlot):
        _translate = QtCore.QCoreApplication.translate
        FormSlot.setWindowTitle(_translate("FormSlot", "Form"))
        self.lbel.setText(_translate("FormSlot", "按下次数："))
        self.btnTest.setText(_translate("FormSlot", "按钮"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSlot = QtWidgets.QWidget()
    ui = Ui_FormSlot()
    ui.setupUi(FormSlot)
    FormSlot.show()
    sys.exit(app.exec())
