# Form implementation generated from reading ui file 'FormSender.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_FormSender(object):
    def setupUi(self, FormSender):
        FormSender.setObjectName("FormSender")
        FormSender.resize(339, 182)
        self.gridLayout = QtWidgets.QGridLayout(FormSender)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSendInt = QtWidgets.QPushButton(parent=FormSender)
        self.btnSendInt.setObjectName("btnSendInt")
        self.gridLayout.addWidget(self.btnSendInt, 2, 0, 1, 1)
        self.btnSendText = QtWidgets.QPushButton(parent=FormSender)
        self.btnSendText.setObjectName("btnSendText")
        self.gridLayout.addWidget(self.btnSendText, 0, 0, 1, 1)
        self.btnSendFloat = QtWidgets.QPushButton(parent=FormSender)
        self.btnSendFloat.setObjectName("btnSendFloat")
        self.gridLayout.addWidget(self.btnSendFloat, 3, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=FormSender)
        self.doubleSpinBox.setProperty("value", 1.23)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 3, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(parent=FormSender)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=FormSender)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.retranslateUi(FormSender)
        QtCore.QMetaObject.connectSlotsByName(FormSender)

    def retranslateUi(self, FormSender):
        _translate = QtCore.QCoreApplication.translate
        FormSender.setWindowTitle(_translate("FormSender", "FormSender"))
        self.btnSendInt.setText(_translate("FormSender", "发送整数"))
        self.btnSendText.setText(_translate("FormSender", "发送文本"))
        self.btnSendFloat.setText(_translate("FormSender", "发送小数"))
        self.lineEdit.setText(_translate("FormSender", "abc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSender = QtWidgets.QWidget()
    ui = Ui_FormSender()
    ui.setupUi(FormSender)
    FormSender.show()
    sys.exit(app.exec())
