# Form implementation generated from reading ui file 'FormReceiver.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormReceiver(object):
    def setupUi(self, FormReceiver):
        FormReceiver.setObjectName("FormReceiver")
        FormReceiver.resize(339, 182)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormReceiver)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtEditReceiver = QtWidgets.QTextEdit(parent=FormReceiver)
        self.txtEditReceiver.setObjectName("txtEditReceiver")
        self.verticalLayout.addWidget(self.txtEditReceiver)
        self.btnOpenChild = QtWidgets.QPushButton(parent=FormReceiver)
        self.btnOpenChild.setObjectName("btnOpenChild")
        self.verticalLayout.addWidget(self.btnOpenChild)

        self.retranslateUi(FormReceiver)
        QtCore.QMetaObject.connectSlotsByName(FormReceiver)

    def retranslateUi(self, FormReceiver):
        _translate = QtCore.QCoreApplication.translate
        FormReceiver.setWindowTitle(_translate("FormReceiver", "FormReceiver"))
        self.btnOpenChild.setText(_translate("FormReceiver", "打开子窗口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormReceiver = QtWidgets.QWidget()
    ui = Ui_FormReceiver()
    ui.setupUi(FormReceiver)
    FormReceiver.show()
    sys.exit(app.exec())
