# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.resize(297, 212)
        mainForm.setStyleSheet("")
        self.label = QtWidgets.QLabel(parent=mainForm)
        self.label.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=mainForm)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.lEditAccount = QtWidgets.QLineEdit(parent=mainForm)
        self.lEditAccount.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.lEditAccount.setStyleSheet("")
        self.lEditAccount.setObjectName("lEditAccount")
        self.lEditCode = QtWidgets.QLineEdit(parent=mainForm)
        self.lEditCode.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.lEditCode.setStyleSheet("")
        self.lEditCode.setObjectName("lEditCode")

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "Form"))
        self.label.setText(_translate("mainForm", "账号"))
        self.label_2.setText(_translate("mainForm", "密码"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainForm = QtWidgets.QWidget()
    ui = Ui_mainForm()
    ui.setupUi(mainForm)
    mainForm.show()
    sys.exit(app.exec())
