# Form implementation generated from reading ui file 'absLayout.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormDemo(object):
    def setupUi(self, FormDemo):
        FormDemo.setObjectName("FormDemo")
        FormDemo.resize(498, 321)
        self.btnScissors = QtWidgets.QPushButton(parent=FormDemo)
        self.btnScissors.setGeometry(QtCore.QRect(130, 240, 101, 31))
        self.btnScissors.setObjectName("btnScissors")
        self.btnStone = QtWidgets.QPushButton(parent=FormDemo)
        self.btnStone.setGeometry(QtCore.QRect(250, 240, 101, 31))
        self.btnStone.setObjectName("btnStone")
        self.btnCloth = QtWidgets.QPushButton(parent=FormDemo)
        self.btnCloth.setGeometry(QtCore.QRect(360, 240, 101, 31))
        self.btnCloth.setObjectName("btnCloth")

        self.retranslateUi(FormDemo)
        QtCore.QMetaObject.connectSlotsByName(FormDemo)

    def retranslateUi(self, FormDemo):
        _translate = QtCore.QCoreApplication.translate
        FormDemo.setWindowTitle(_translate("FormDemo", "绝对布局"))
        self.btnScissors.setText(_translate("FormDemo", "剪刀"))
        self.btnStone.setText(_translate("FormDemo", "石头"))
        self.btnCloth.setText(_translate("FormDemo", "布"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormDemo = QtWidgets.QWidget()
    ui = Ui_FormDemo()
    ui.setupUi(FormDemo)
    FormDemo.show()
    sys.exit(app.exec())
