# Form implementation generated from reading ui file 'FormHello.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormHello(object):
    def setupUi(self, FormHello):
        FormHello.setObjectName("FormHello")
        FormHello.resize(469, 345)
        self.btnHelloWorld = QtWidgets.QPushButton(parent=FormHello)
        self.btnHelloWorld.setGeometry(QtCore.QRect(160, 140, 101, 31))
        self.btnHelloWorld.setObjectName("btnHelloWorld")

        self.retranslateUi(FormHello)
        QtCore.QMetaObject.connectSlotsByName(FormHello)

    def retranslateUi(self, FormHello):
        _translate = QtCore.QCoreApplication.translate
        FormHello.setWindowTitle(_translate("FormHello", "Form"))
        self.btnHelloWorld.setText(_translate("FormHello", "hello world!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormHello = QtWidgets.QWidget()
    ui = Ui_FormHello()
    ui.setupUi(FormHello)
    FormHello.show()
    sys.exit(app.exec())
