# Form implementation generated from reading ui file 'UDFSlot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormSlot(object):
    def setupUi(self, FormSlot):
        FormSlot.setObjectName("FormSlot")
        FormSlot.resize(440, 103)
        self.gridLayout = QtWidgets.QGridLayout(FormSlot)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=FormSlot)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtnWatermelon = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbtnWatermelon.setObjectName("rbtnWatermelon")
        self.horizontalLayout.addWidget(self.rbtnWatermelon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.rbtnBanana = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbtnBanana.setObjectName("rbtnBanana")
        self.horizontalLayout.addWidget(self.rbtnBanana, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.rbtnOrange = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbtnOrange.setObjectName("rbtnOrange")
        self.horizontalLayout.addWidget(self.rbtnOrange, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.lbel = QtWidgets.QLabel(parent=FormSlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbel.sizePolicy().hasHeightForWidth())
        self.lbel.setSizePolicy(sizePolicy)
        self.lbel.setObjectName("lbel")
        self.gridLayout.addWidget(self.lbel, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=FormSlot)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)

        self.retranslateUi(FormSlot)
        QtCore.QMetaObject.connectSlotsByName(FormSlot)

    def retranslateUi(self, FormSlot):
        _translate = QtCore.QCoreApplication.translate
        FormSlot.setWindowTitle(_translate("FormSlot", "Form"))
        self.groupBox.setTitle(_translate("FormSlot", "请选择水果"))
        self.rbtnWatermelon.setText(_translate("FormSlot", "西瓜"))
        self.rbtnBanana.setText(_translate("FormSlot", "香蕉"))
        self.rbtnOrange.setText(_translate("FormSlot", "橘子"))
        self.lbel.setText(_translate("FormSlot", "您选择了："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSlot = QtWidgets.QWidget()
    ui = Ui_FormSlot()
    ui.setupUi(FormSlot)
    FormSlot.show()
    sys.exit(app.exec())
